// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "./SkillRegistry.sol";

/**
 * @title SkillPayment
 * @notice Handles pay-per-call AVAX payments — the on-chain side of x402.
 *
 * x402 flow:
 *   1. Agent backend sends HTTP request to SkillMint with x402 Payment header
 *   2. SkillMint backend verifies the on-chain payment (this contract)
 *   3. On confirmed SkillCalled event → executes Claude API with skill JSON
 *   4. Returns response to agent
 *
 * Payment split: 90% creator · 10% treasury
 * Creator identity is retrieved via SkillRegistry.getSkillOwner()
 * (works even for anonymous skills — wallet is always stored on-chain)
 */
contract SkillPayment is Ownable, ReentrancyGuard {

    // ─── State ────────────────────────────────────────────────────────────────

    SkillRegistry public registry;
    address       public treasury;
    uint256       public platformFeeBps = 1000; // 10%

    // ─── Events ───────────────────────────────────────────────────────────────

    /**
     * @notice Emitted on every successful paid call.
     *
     * @param skillId       Registry ID of the skill
     * @param caller        Agent wallet that paid
     * @param totalPaid     Total AVAX sent (wei)
     * @param creatorShare  Forwarded to skill owner (wei)
     * @param platformShare Forwarded to treasury (wei)
     * @param requestId     Unique call ID — backend uses this to correlate
     *                      the x402 HTTP request with this on-chain event
     */
    event SkillCalled(
        uint256 indexed skillId,
        address indexed caller,
        uint256 totalPaid,
        uint256 creatorShare,
        uint256 platformShare,
        bytes32 requestId
    );

    // ─── Constructor ──────────────────────────────────────────────────────────

   constructor(address _registry, address _treasury) {
        registry = SkillRegistry(_registry);
        treasury = _treasury;
    }

    // ─── Core ─────────────────────────────────────────────────────────────────

    /**
     * @notice Pay for and trigger a skill call.
     *
     * @param skillId    ID from SkillRegistry
     * @param requestId  bytes32 generated by the caller (e.g. keccak256(abi.encodePacked(block.timestamp, msg.sender, skillId)))
     *                   Must be unique per call. Backend matches this to the pending x402 HTTP request.
     *
     * msg.value must equal skill.pricePerCall exactly.
     */
    function callSkill(uint256 skillId, bytes32 requestId)
        external payable nonReentrant
    {
        // Fetch prices from registry (public — no auth needed)
        (uint256 pricePerCall,) = registry.getPrices(skillId);

        require(registry.isActive(skillId),   "skill is inactive");
        require(msg.value == pricePerCall,     "incorrect payment");

        // Split
        uint256 platformShare = (msg.value * platformFeeBps) / 10_000;
        uint256 creatorShare  = msg.value - platformShare;

        // Route funds — owner retrieved via privileged call (works for anon skills)
        address creator = registry.getSkillOwner(skillId);
        (bool okCreator,)  = payable(creator).call{value: creatorShare}("");
        (bool okTreasury,) = payable(treasury).call{value: platformShare}("");
        require(okCreator && okTreasury, "transfer failed");

        // Update call count
        registry.incrementCallCount(skillId);

        emit SkillCalled(skillId, msg.sender, msg.value, creatorShare, platformShare, requestId);
    }

    // ─── Admin ────────────────────────────────────────────────────────────────

    function setTreasury(address _treasury) external onlyOwner {
        treasury = _treasury;
    }

    function setPlatformFee(uint256 bps) external onlyOwner {
        require(bps <= 2000, "max 20%");
        platformFeeBps = bps;
    }
}
